let employees = [{ "id": 1, "first_name": "Don", "email": "dbrady0@mashable.com", "gender": "Male" },
{ "id": 2, "first_name": "Lisabeth", "email": "lklos1@dropbox.com", "gender": "Non-binary" },
{ "id": 3, "first_name": "Bald", "email": "bburkman2@example.com", "gender": "Male" },
{ "id": 4, "first_name": "Livvie", "email": "lfeary3@disqus.com", "gender": "Female" },
{ "id": 5, "first_name": "Iolande", "email": "imarty4@cpanel.net", "gender": "Female" },
{ "id": 6, "first_name": "Steffane", "email": "sbodiam5@nsw.gov.au", "gender": "Female" },
{ "id": 7, "first_name": "Marina", "email": "melverstone6@nifty.com", "gender": "Female" },
{ "id": 8, "first_name": "Temp", "email": "tbeebee7@techcrunch.com", "gender": "Male" },
{ "id": 9, "first_name": "Rosabella", "email": "rclilverd8@google.pl", "gender": "Female" },
{ "id": 10, "first_name": "Deb", "email": "dmalcher9@nyu.edu", "gender": "Female" },
{ "id": 11, "first_name": "Nanon", "email": "ntittertona@flavors.me", "gender": "Female" },
{ "id": 12, "first_name": "Jacquette", "email": "jferranb@flickr.com", "gender": "Bigender" },
{ "id": 13, "first_name": "Corina", "email": "cvinsenc@miibeian.gov.cn", "gender": "Female" },
{ "id": 14, "first_name": "Imogene", "email": "ipoultond@weebly.com", "gender": "Female" },
{ "id": 15, "first_name": "Gianna", "email": "gtallboye@reverbnation.com", "gender": "Female" },
{ "id": 16, "first_name": "Jody", "email": "jdepinnaf@google.com.br", "gender": "Genderqueer" },
{ "id": 17, "first_name": "Cassie", "email": "cmcknielyg@google.ca", "gender": "Male" },
{ "id": 18, "first_name": "Lars", "email": "lrockwillh@smh.com.au", "gender": "Male" },
{ "id": 19, "first_name": "Rudiger", "email": "rvelai@mysql.com", "gender": "Male" },
{ "id": 20, "first_name": "Brandise", "email": "btoulamainj@webnode.com", "gender": "Female" },
{ "id": 21, "first_name": "Jae", "email": "jbartalik@cbsnews.com", "gender": "Male" },
{ "id": 22, "first_name": "Joleen", "email": "jilivel@fema.gov", "gender": "Female" },
{ "id": 23, "first_name": "Angelo", "email": "aranbym@mlb.com", "gender": "Male" },
{ "id": 24, "first_name": "Marve", "email": "mpetettn@redcross.org", "gender": "Male" },
{ "id": 25, "first_name": "Raddy", "email": "rdunlapo@linkedin.com", "gender": "Male" },
{ "id": 26, "first_name": "Sterne", "email": "speizerp@google.pl", "gender": "Male" },
{ "id": 27, "first_name": "Jessica", "email": "jfrancescq@nsw.gov.au", "gender": "Female" },
{ "id": 28, "first_name": "Frederique", "email": "fdrohaner@hexun.com", "gender": "Female" },
{ "id": 29, "first_name": "Joyce", "email": "jgorrissens@furl.net", "gender": "Female" },
{ "id": 30, "first_name": "Palm", "email": "parlottt@abc.net.au", "gender": "Agender" },
{ "id": 31, "first_name": "Gilbertina", "email": "gspensleyu@g.co", "gender": "Female" },
{ "id": 32, "first_name": "Darline", "email": "dcarderv@globo.com", "gender": "Female" },
{ "id": 33, "first_name": "Sarita", "email": "snorwellw@youtube.com", "gender": "Female" },
{ "id": 34, "first_name": "Marcus", "email": "mcarriagex@google.com.br", "gender": "Male" },
{ "id": 35, "first_name": "Diannne", "email": "dnordassy@amazon.co.jp", "gender": "Female" },
{ "id": 36, "first_name": "Luelle", "email": "ldepaoliz@usda.gov", "gender": "Genderfluid" },
{ "id": 37, "first_name": "Torie", "email": "tday10@icio.us", "gender": "Female" },
{ "id": 38, "first_name": "Helena", "email": "htotton11@photobucket.com", "gender": "Non-binary" },
{ "id": 39, "first_name": "Pavel", "email": "pjewes12@elpais.com", "gender": "Male" },
{ "id": 40, "first_name": "Bartel", "email": "belvey13@geocities.com", "gender": "Genderfluid" },
{ "id": 41, "first_name": "Anissa", "email": "alayland14@addthis.com", "gender": "Female" },
{ "id": 42, "first_name": "Cirillo", "email": "cjakubczyk15@about.me", "gender": "Agender" },
{ "id": 43, "first_name": "Patrice", "email": "pdeville16@psu.edu", "gender": "Agender" },
{ "id": 44, "first_name": "Hymie", "email": "hwortley17@jigsy.com", "gender": "Male" },
{ "id": 45, "first_name": "Wyn", "email": "wpolding18@ustream.tv", "gender": "Male" },
{ "id": 46, "first_name": "Ricardo", "email": "rbevington19@example.com", "gender": "Male" },
{ "id": 47, "first_name": "Emmye", "email": "eprobets1a@w3.org", "gender": "Genderqueer" },
{ "id": 48, "first_name": "Sephira", "email": "slandre1b@is.gd", "gender": "Female" },
{ "id": 49, "first_name": "Rose", "email": "rbraffington1c@foxnews.com", "gender": "Female" },
{ "id": 50, "first_name": "Jinny", "email": "jmoneypenny1d@ibm.com", "gender": "Female" },
{ "id": 51, "first_name": "Valeria", "email": "vshakeshaft1e@wordpress.com", "gender": "Female" },
{ "id": 52, "first_name": "Hyacintha", "email": "hfanshaw1f@nih.gov", "gender": "Female" },
{ "id": 53, "first_name": "Jocko", "email": "jwein1g@ebay.co.uk", "gender": "Male" },
{ "id": 54, "first_name": "Hilarius", "email": "hsitlinton1h@telegraph.co.uk", "gender": "Male" },
{ "id": 55, "first_name": "Rosemarie", "email": "rlaxton1i@bigcartel.com", "gender": "Female" },
{ "id": 56, "first_name": "Kilian", "email": "kmeriet1j@fema.gov", "gender": "Genderfluid" },
{ "id": 57, "first_name": "Kiley", "email": "kbenazet1k@wikia.com", "gender": "Male" },
{ "id": 58, "first_name": "Isidro", "email": "istollmeier1l@nature.com", "gender": "Male" },
{ "id": 59, "first_name": "Raimund", "email": "rconeau1m@ning.com", "gender": "Male" },
{ "id": 60, "first_name": "Dorian", "email": "dnarramor1n@wikia.com", "gender": "Female" },
{ "id": 61, "first_name": "Howard", "email": "hsolomonides1o@tmall.com", "gender": "Male" },
{ "id": 62, "first_name": "Etan", "email": "emccuish1p@alibaba.com", "gender": "Male" },
{ "id": 63, "first_name": "Cathrine", "email": "colenin1q@businesswire.com", "gender": "Female" },
{ "id": 64, "first_name": "Georgi", "email": "gwasbrough1r@jalbum.net", "gender": "Genderqueer" },
{ "id": 65, "first_name": "Agnola", "email": "akayley1s@dot.gov", "gender": "Female" },
{ "id": 66, "first_name": "Valentine", "email": "vclausius1t@yellowbook.com", "gender": "Female" },
{ "id": 67, "first_name": "Niall", "email": "nsavage1u@adobe.com", "gender": "Male" },
{ "id": 68, "first_name": "Tamara", "email": "tseven1v@networkadvertising.org", "gender": "Female" },
{ "id": 69, "first_name": "Arlinda", "email": "apeers1w@dmoz.org", "gender": "Female" },
{ "id": 70, "first_name": "Darill", "email": "dstaten1x@clickbank.net", "gender": "Male" },
{ "id": 71, "first_name": "Madel", "email": "mlacey1y@google.com.br", "gender": "Bigender" },
{ "id": 72, "first_name": "Renaud", "email": "rmordacai1z@alibaba.com", "gender": "Male" },
{ "id": 73, "first_name": "Gianna", "email": "gfidian20@nba.com", "gender": "Female" },
{ "id": 74, "first_name": "Der", "email": "dsoames21@wiley.com", "gender": "Male" },
{ "id": 75, "first_name": "Claudette", "email": "ctreher22@businessweek.com", "gender": "Female" },
{ "id": 76, "first_name": "Rozelle", "email": "rgiraldez23@uiuc.edu", "gender": "Female" },
{ "id": 77, "first_name": "Yule", "email": "ywapol24@hostgator.com", "gender": "Male" },
{ "id": 78, "first_name": "Ruttger", "email": "rbuche25@aboutads.info", "gender": "Genderqueer" },
{ "id": 79, "first_name": "Tillie", "email": "tlavigne26@cbsnews.com", "gender": "Female" },
{ "id": 80, "first_name": "Jacky", "email": "jendicott27@networksolutions.com", "gender": "Male" },
{ "id": 81, "first_name": "Stacy", "email": "srein28@springer.com", "gender": "Male" },
{ "id": 82, "first_name": "Dougie", "email": "dferrarini29@github.com", "gender": "Male" },
{ "id": 83, "first_name": "Ethelind", "email": "ewinslet2a@nsw.gov.au", "gender": "Female" },
{ "id": 84, "first_name": "Gale", "email": "geverly2b@google.ru", "gender": "Male" },
{ "id": 85, "first_name": "Faulkner", "email": "fglenwright2c@studiopress.com", "gender": "Male" },
{ "id": 86, "first_name": "Nara", "email": "nfilintsev2d@tinypic.com", "gender": "Female" },
{ "id": 87, "first_name": "Alane", "email": "ascaysbrook2e@washingtonpost.com", "gender": "Female" },
{ "id": 88, "first_name": "Perry", "email": "pmoore2f@ovh.net", "gender": "Male" },
{ "id": 89, "first_name": "Dalston", "email": "dkernell2g@chron.com", "gender": "Male" },
{ "id": 90, "first_name": "Chandler", "email": "cangelini2h@goo.ne.jp", "gender": "Male" },
{ "id": 91, "first_name": "Deni", "email": "dwessing2i@typepad.com", "gender": "Female" },
{ "id": 92, "first_name": "Trip", "email": "twallis2j@oaic.gov.au", "gender": "Male" },
{ "id": 93, "first_name": "Josie", "email": "jconnell2k@jalbum.net", "gender": "Female" },
{ "id": 94, "first_name": "Tris", "email": "tattenbarrow2l@51.la", "gender": "Male" },
{ "id": 95, "first_name": "Alexi", "email": "alefriec2m@rambler.ru", "gender": "Agender" },
{ "id": 96, "first_name": "Farlee", "email": "fkatte2n@facebook.com", "gender": "Genderqueer" },
{ "id": 97, "first_name": "Herrick", "email": "hbosch2o@ycombinator.com", "gender": "Male" },
{ "id": 98, "first_name": "Kalie", "email": "klerner2p@ucsd.edu", "gender": "Female" },
{ "id": 99, "first_name": "Saundra", "email": "seglington2q@sun.com", "gender": "Female" },
{ "id": 100, "first_name": "Henriette", "email": "hlepiscopio2r@istockphoto.com", "gender": "Female" }]


function displayData() {

  let rows = ""


  for (emp of employees) {
    let website = emp.email.substr(emp.email.indexOf('@') + 1)
    rows = rows + `<tr> 
                   <td>  ${emp.id}</td>
                   <td>  ${emp.first_name}</td>
                   <td>  ${emp.email}</td>
                   <td>  ${emp.gender}</td>
                   <td>  ${website}</td>
                   <td>  ${emp.email.substr(0, emp.email.indexOf('@')+2)}</td>
                 </tr>`

  }
  document.getElementById("tbodydata").innerHTML = rows
}